/*
 * Jira Software Data Center REST API Reference
 *
 * This is the reference document for the REST API and resources provided by Jira Software Data Center. The REST APIs are for developers who want to integrate Jira Data Center with other applications, and for administrators who want to script configuration interactions with Jira Data Center.  Jira Data Center is built upon the Jira platform.  As such there is a natural overlap in functionality between what is provided by Jira Data Center and what is provided by the Jira platform.  If you are after an introductory, high-level view of the Jira REST APIs, then the best place to start is the [Jira REST API home](https://developer.atlassian.com/server/jira/platform/rest-apis/). ## Using the REST API Not familiar with the Jira Data Center REST APIs? Start with our [Guide to exploring the Jira Data Center domain model via the REST APIs](https://developer.atlassian.com/server/jira/platform/tutorials_and_guides/), which will help you get a conceptual understanding of the Jira Data Center REST APIs.  If you want instructions on how to use the REST APIs, check out the [Appendix](#appendix) at the end of this page (after the resources), where you'll find information on the following topics: * [Structure of the REST URIs](#structure) * [Authentication](#authentication) * [Pagination](#pagination) * [Expansion](#expansion) * [Special headers](#special-headers) * [Field input formats](#fieldformats) ### Experimental methods Methods marked as `EXPERIMENTAL` may change without notice. We are looking for your feedback for these methods. To use experimental methods, you must set this header in your requests: `X-ExperimentalApi : true`. This indicates that you are opting into the experimental preview. Once a resource or method moves out of the experimental phase, then this header will no longer be required nor checked. 
 *
 * The version of the OpenAPI document: swagger-merged-template.yaml
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_avatar_from_temporary3`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAvatarFromTemporary3Error {
    Status400(),
    Status403(),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_avatar1`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAvatar1Error {
    Status400(),
    Status403(),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_avatars`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAvatarsError {
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`store_temporary_avatar_using_multi_part2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StoreTemporaryAvatarUsingMultiPart2Error {
    Status400(),
    Status403(),
    Status404(),
    UnknownValue(serde_json::Value),
}


/// Creates avatar from temporary
pub async fn create_avatar_from_temporary3(configuration: &configuration::Configuration, r#type: &str, owning_object_id: &str, avatar_cropping_bean: Option<models::AvatarCroppingBean>) -> Result<models::AvatarBean, Error<CreateAvatarFromTemporary3Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_type = r#type;
    let p_owning_object_id = owning_object_id;
    let p_avatar_cropping_bean = avatar_cropping_bean;

    let uri_str = format!("{}/api/2/universal_avatar/type/{type}/owner/{owningObjectId}/avatar", configuration.base_path, type=crate::apis::urlencode(p_type), owningObjectId=crate::apis::urlencode(p_owning_object_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    req_builder = req_builder.json(&p_avatar_cropping_bean);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AvatarBean`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AvatarBean`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateAvatarFromTemporary3Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Deletes avatar
pub async fn delete_avatar1(configuration: &configuration::Configuration, id: i64, r#type: &str, owning_object_id: &str) -> Result<(), Error<DeleteAvatar1Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_id = id;
    let p_type = r#type;
    let p_owning_object_id = owning_object_id;

    let uri_str = format!("{}/api/2/universal_avatar/type/{type}/owner/{owningObjectId}/avatar/{id}", configuration.base_path, id=p_id, type=crate::apis::urlencode(p_type), owningObjectId=crate::apis::urlencode(p_owning_object_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteAvatar1Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of all avatars
pub async fn get_avatars(configuration: &configuration::Configuration, r#type: &str, owning_object_id: &str) -> Result<models::AvatarBean, Error<GetAvatarsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_type = r#type;
    let p_owning_object_id = owning_object_id;

    let uri_str = format!("{}/api/2/universal_avatar/type/{type}/owner/{owningObjectId}", configuration.base_path, type=crate::apis::urlencode(p_type), owningObjectId=crate::apis::urlencode(p_owning_object_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AvatarBean`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AvatarBean`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAvatarsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Creates temporary avatar
pub async fn store_temporary_avatar_using_multi_part2(configuration: &configuration::Configuration, r#type: &str, owning_object_id: &str, content_type: Option<&str>, form_field: Option<bool>, input_stream: Option<serde_json::Value>, name: Option<&str>, size: Option<i64>, value: Option<&str>) -> Result<models::AvatarCroppingBean, Error<StoreTemporaryAvatarUsingMultiPart2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_type = r#type;
    let p_owning_object_id = owning_object_id;
    let p_content_type = content_type;
    let p_form_field = form_field;
    let p_input_stream = input_stream;
    let p_name = name;
    let p_size = size;
    let p_value = value;

    let uri_str = format!("{}/api/2/universal_avatar/type/{type}/owner/{owningObjectId}/temp", configuration.base_path, type=crate::apis::urlencode(p_type), owningObjectId=crate::apis::urlencode(p_owning_object_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form = reqwest::multipart::Form::new();
    if let Some(param_value) = p_content_type {
        multipart_form = multipart_form.text("contentType", param_value.to_string());
    }
    if let Some(param_value) = p_form_field {
        multipart_form = multipart_form.text("formField", param_value.to_string());
    }
    if let Some(param_value) = p_input_stream {
        multipart_form = multipart_form.text("inputStream", param_value.to_string());
    }
    if let Some(param_value) = p_name {
        multipart_form = multipart_form.text("name", param_value.to_string());
    }
    if let Some(param_value) = p_size {
        multipart_form = multipart_form.text("size", param_value.to_string());
    }
    if let Some(param_value) = p_value {
        multipart_form = multipart_form.text("value", param_value.to_string());
    }
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AvatarCroppingBean`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AvatarCroppingBean`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StoreTemporaryAvatarUsingMultiPart2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

